# Generated by Django 4.2.26 on 2026-02-27 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expense_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicShareLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("MONTH", "MONTH"),
                            ("RANGE", "RANGE"),
                            ("PERSON_MONTH", "PERSON_MONTH"),
                            ("PERSON_RANGE", "PERSON_RANGE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_payload", models.JSONField(default=dict)),
                ("permissions", models.JSONField(default=dict)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
