name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - stage
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: Ponta-Development/studio-ci/.github/workflows/ci-django.yml@main
    with:
      service_name: expense-tracker
      django_settings_module: config.settings
    secrets: inherit
